### ISSUE TITLE
pro create 报错

### ISSUE THREAD

**Issue by 868618** [ant-design/ant-design-pro-cli#110]
`kenny@kennydeMBP test % pro create test
? 🐂 使用 umi@4 还是 umi@3 ? umi@4
🧎🏻全量区块暂时不支持 umi@4
Cloning into 'test'...
fatal: unable to access 'https://github.com/ant-design/ant-design-pro/': Failed to connect to github.com port 443 after 3 ms: Connection refused
/usr/local/lib/node_modules/@ant-design/pro-cli/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 128: git clone https://github.com/ant-design/ant-design-pro --depth=1 test
    at makeError (/usr/local/lib/node_modules/@ant-design/pro-cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/usr/local/lib/node_modules/@ant-design/pro-cli/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AntDesignProGenerator.writing (/usr/local/lib/node_modules/@ant-design/pro-cli/src/create/generators/ant-design-pro/index.js:108:5) {
  shortMessage: 'Command failed with exit code 128: git clone https://github.com/ant-design/ant-design-pro --depth=1 test',
  command: 'git clone https://github.com/ant-design/ant-design-pro --depth=1 test',
  escapedCommand: 'git clone "https://github.com/ant-design/ant-design-pro" "--depth=1" test',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
`

**Comment by GeoDaoyu** [comment]
网络问题，无法链接到https://github.com/ant-design/ant-design-pro/
请检查网络，并重新尝试。
